### PR TITLE
Optional dependencies for transports

### PR DESCRIPTION
**Pull request by leszekhanusz**
See issue #147

### CODE REVIEW

**Comment by leszekhanusz** [comment]
Of course we'll need to document this before it is merged as it is a breaking change.

**Comment by leszekhanusz** [comment]
I'm starting to think that my PR #112 was actually a bad idea. We could still revert it as we are still in alpha?

**Comment by KingDarBoja** [comment]
Seems to be the same setup as I did at [graphql-server](https://github.com/graphql-python/graphql-server/blob/master/setup.py) but I am curious about the usage of [with supress](https://docs.python.org/3/library/contextlib.html#contextlib.suppress) statement in order to keep running the program if the user has not installed any "required" extras.

Regarding PR #112, well since you want to alert users to install required packages in order to use specific transports, the export should be keep on the same module scope, in other words, with this change it should avoid including all transports on global export (`__init__.py`).

**Comment by leszekhanusz** [comment]
> Seems to be the same setup as I did at [graphql-server](https://github.com/graphql-python/graphql-server/blob/master/setup.py)

That's because I copied it from there :laughing:

**Comment by KingDarBoja** [comment]
@leszekhanusz are you going to revert the #112 on this PR so it is two birds, one shot? 👓

**Comment by leszekhanusz** [comment]
> @leszekhanusz are you going to revert the #112 on this PR so it is two birds, one shot?

Yes

**Comment by leszekhanusz** [comment]
I modified the tests so that you can run tests with only a single transport dependency.
To do that:
* create a new python environment
* Install the dependencies for a single transport
* run the tests with the flag --aiohttp-only, --websockets-only or --requests-only depending on the selected dependency

to install test dependencies for only websockets for example:
```
pip install .[websockets,test_no_transport]
```

**Comment by leszekhanusz** [comment]
Now I still need to add GitHub actions to test this automatically

**Pull request merged**
