### PR TITLE
Chore update graphql core to 3.3.0 and dropping support for Python 3.6

### PR DESCRIPTION
**Pull request by leszekhanusz**
* Following [graphql-core update to 3.3.0a1](https://github.com/graphql-python/graphql-core/releases/tag/v3.3.0a1)
* Adding spaces in tests following graphql-core update
* Dropping support for Python 3.6

### CODE REVIEW

**Comment by leszekhanusz** [comment]
@Cito any idea why pypy3 cannot find graphql-core version 3.3.0a1 ?

**Comment by danvendia** [comment]
@leszekhanusz is this PR ready to ship?  I'd love to get a new release of gql with a setup.py version bump of graphql-core that allows 3.3 to work (https://github.com/graphql-python/gql/blob/master/setup.py#L6).

**Comment by leszekhanusz** [comment]
> @leszekhanusz is this PR ready to ship? I'd love to get a new release of gql with a setup.py version bump of graphql-core that allows 3.3 to work (https://github.com/graphql-python/gql/blob/master/setup.py#L6).

graphql-core 3.3 is still in alpha. I was thinking about waiting until a stable graphql-core release before merging this PR and making a new gql release.

But we could make a gql pre-release.

@Cito What do you think, should I make a gql pre-release `3.5.0a0` ?

**Comment by danvendia** [comment]
> > @leszekhanusz is this PR ready to ship? I'd love to get a new release of gql with a setup.py version bump of graphql-core that allows 3.3 to work (https://github.com/graphql-python/gql/blob/master/setup.py#L6).
> 
> graphql-core 3.3 is still in alpha. I was thinking about waiting until a stable graphql-core release before merging this PR and making a new gql release.
> 
> But we could make a gql pre-release.
> 
> @Cito What do you think, should I make a gql pre-release `3.5.0a0` ?

A pre-release of gql would be awesome if it makes sense 👍

**Comment by Cito** [comment]
> @Cito What do you think, should I make a gql pre-release `3.5.0a0` ?

That would be great, in order to find any incompatibilities and to test the new features in core 3.3.

**Comment by leszekhanusz** [comment]
> A pre-release of gql would be awesome if it makes sense +1

[Pre-Release v3.5.0a0](https://github.com/graphql-python/gql/releases/tag/v3.5.0a0) is now available.

**Comment by danvendia** [comment]
Thanks so much @leszekhanusz! Really appreciate it

**Pull request merged**
