### PR TITLE
DSL implementation of fragments

### PR DESCRIPTION
**Pull request by Cito**
This is my suggestion for #198

### CODE REVIEW

**Comment by leszekhanusz** [comment]
> Sorry, I must leave it to you or others to work out the details due to lack of time. I just wanted to provide a rough idea how this can be implemented.

Ok, no worries, I'll propose something.

**Comment by chadfurman** [comment]
I also would be interested in helping if the work isn't all done at this point

**Comment by chadfurman** [comment]
Checking in to avoid duplicate efforts.  I'm setting up my local env right now and going to read over the code in https://github.com/graphql-python/gql/commit/d505962abdb4795e76f994ef93a80b7e3fae8df4 plus try and get a basic inline fragment to run + run the tests + evaluate the above comment against the commit.

**Comment by leszekhanusz** [comment]
@chadfurman 
Now that I've started working on this, I would like to finish it. I hope you don't mind.

I am currently looking at how we could also support normal fragments into this PR.

That's when I realized that the `DSLSelection` class was actually used for two different purposes:
 - for elements which can be arguments of the select method (selectable elements)
 - for elements on which we can use the select method (containers)

So I decided to split it into DSLSelectable and DSLSelector.

Next I am going to introduce the `FragmentSpreadNode` and `FragmentDefinitionNode` from graphql-core AST.

**Comment by chadfurman** [comment]
Not a problem!  Ping me if you want help on anything -- this or another ticket   I'll switch tasks 

Thank you for your effort and time :)

**Comment by leszekhanusz** [comment]
> Not a problem! Ping me if you want help on anything -- this or another ticket. For now, I'll switch tasks
> 
> Thank you for your effort and time :)
> 
> fwiw: I have my local env setup and all dev deps on the right version now w/ tests and `make check` all fine sweat_smile
> 
> You have a very solid project here. Great work.

Thanks! If you want something to do, you could maybe check the issue #125, diving into the Appsync protocol and creating another transport AWSAppsyncTransport which inherits WebsocketsTransport.

**Comment by leszekhanusz** [comment]
>     * Not sure if the DSL should really expose different objects for inline and named fragments. The distinction could be actually left transparent to the user, e.g. the dsl_gql function could optimize automatically by using named fragments instead of inline fragments. For the users of the DSL it makes no difference, since they can create fragment objects once and reuse them anyway, without needing to explicitly create named fragments.

@Cito I tried to combine normal and inline fragments in a single class but they are really different beasts, with normal fragments which need a name and can have variables.
With my current code, if you use a `DSLFragment` in dsl_gql, you'll get a `FragmentDefinitionNode`, but if you use it as an argument of a select, then you get a `FragmentSpreadNode`

So now we need to know when we use a fragment as an argument in a `select` whether this is a normal fragment, and in this case we return a `FragmentSpreadNode` or whether it is an inline fragment and we return an `InlineFragmentNode`. If we used the same class, we could detect it somehow by checking if the fragment has a name, but it might get confusing and I think it is better that we stay explicit here.

**Comment by Cito** [comment]
> with normal fragments which need a name and can have variables

But as far as I see, fragments with vars were experimental only (not part of the spec) and have now been [deprecated](https://github.com/graphql/graphql-js/pull/2920) in Graphql.js (and hence in GraphQL-core as well).

**Comment by leszekhanusz** [comment]
Interesting... But the main problem remains and it feels cleaner to me to keep the classes separate.
What do you think of the current state of this PR? Is this something we could agree on?

**Comment by Cito** [comment]
LGTM, it's definitely cleaner and allows more control over the generated query.

**Comment by leszekhanusz** [comment]
Good! I'll add some documentation and merge this PR next weekend.

**Comment by vedantpuri** [comment]
@leszekhanusz  Any updates on this ?

**Review by leszekhanusz — APPROVED** [review]

**Pull request merged**
