### PR TITLE
Fix 4xx error handling

### PR DESCRIPTION
**Pull request by abhishek-12355**
Fixes graphql-python/gql#194

### CODE REVIEW

**Comment by abhishek-12355** [comment]
I've tried fixing the Lint issues. When I run them locally, they don't complain of anything, but on github they are throwing errors.
@syrusakbary @BossGrand @jkimbo

**Comment by leszekhanusz** [comment]
Regarding the linting issues, you probably don't have the correct dev dependencies.
Did you check the [CONTRIBUTING.md ](https://github.com/graphql-python/gql/blob/master/CONTRIBUTING.md)file ?
Once you have the correct dependencies, the linting can be done with `make check`

**Comment by abhishek-12355** [comment]
@leszekhanusz Thanks. It is fixed now.

**Comment by leszekhanusz** [comment]
I made a refactor in order to avoid checking for the content_type. Could you please check that it is ok for you ?

**Review by leszekhanusz — APPROVED** [review]

**Comment by leszekhanusz** [comment]
To resume, here was the situation previously:

```
JSON:
    data or errors keys:
        ExecutionResult
    no data or errors keys:
        TransportProtocolError
Not JSON:
    status < 400:
        TransportProtocolError
    status >= 400:
        TransportServerError
```

Now we have:

```
JSON:
    data or errors keys:
        ExecutionResult
    no data or errors keys:
        status < 400:
            TransportProtocolError
        status >= 400:
            TransportServerError        
Not JSON:
    status < 400:
        TransportProtocolError
    status >= 400:
        TransportServerError
```

Note that we still set an `ExecutionResult` if we receive a correct json with errors keys even if the http code is higher than 400.

**Comment by abhishek-12355** [comment]
> I made a refactor in order to avoid checking for the content_type. Could you please check that it is ok for you ?

Looks good to me.

**Pull request merged**
