### PR TITLE
File support

### PR DESCRIPTION
**Pull request by leszekhanusz**
Continuation of PR #126

Regarding this [issue](https://github.com/graphql-python/gql/issues/68)
Following this [spec](https://github.com/jaydenseric/graphql-multipart-request-spec)
A bunch of code ripped from this [repo](https://github.com/DoctorJohn/aiogqlc/blob/a9567b322e4c8e5f618cc6eb4c1d401666b08708/aiogqlc/client.py)

### CODE REVIEW

**Comment by KingDarBoja** [comment]
The tests will fail on Windows because the EOL character is different:

```console
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "d:\anaconda3\envs\gql-dev\lib\site-packages\aiohttp\web_protocol.py", line 418, in start
    resp = await task
  File "d:\anaconda3\envs\gql-dev\lib\site-packages\aiohttp\web_app.py", line 458, in _handle
    resp = await handler(request)
  File "D:\Programming\py_projects\graphql-python-repos\gql\tests\test_aiohttp.py", line 574, in handler
    assert field_2_text == file_1_content
AssertionError: assert '\r\nThis is a test file\r\nThis file will be sent in the GraphQL mutation\r\n' == '\nThis is a test file\nThis file will be sent in the GraphQL mutation\n'
  -
  +
  - This is a test file
  + This is a test file
  ?                    +
  - This file will be sent in the GraphQL mutation
  + This file will be sent in the GraphQL mutation
  ?                                               +
INFO:aiohttp.access:127.0.0.1 [09/Oct/2020:00:30:40 +0000] "POST / HTTP/1.1" 500 244 "-" "Python/3.8 aiohttp/3.6.2"
```
Everything else looks good to me.

**Review by KingDarBoja — APPROVED** [review]

**Comment by leszekhanusz** [comment]
The tests should be OK now under windows.
@KingDarBoja Could you please test it ? Thanks

**Comment by leszekhanusz** [comment]
@leahein @quasimik @KingDarBoja 
Thanks again for your help with this feature.

**Comment by quasimik** [comment]
I just checked this, apologies for not responding quickly (I didn't set up proper notifications). Anyway, glad to see that it's merged!

**Comment by g-londhe** [comment]
Hi,
Guys I'm trying to upload file with
`{'operationName':"ProductMediaCreate",'variables':{"alt":"","image":"null","product":"product_id"},'query':"fragment ProductErrorFragment on ProductError {  code message  field  __typename}fragment ProductMediaFragment on ProductMedia {  id  alt  sortOrder  url  type  oembedData  __typename}mutation ProductMediaCreate($product: ID!, $image: Upload, $alt: String, $mediaUrl: String) {  productMediaCreate(    input: {alt: $alt, image: $image, product: $product, mediaUrl: $mediaUrl}  ) {    errors {      ...ProductErrorFragment      __typename    }    product {      id      media {        ...ProductMediaFragment        __typename      }      __typename    }    __typename  }}"}`

to saleor but I'm getting "unable to parse the query" even for working(POSTMAN) query `"{"operationName":"FileUpload","variables":{"file":null},"query":"fragment FileFragment on File { url  contentType  __typename}fragment UploadErrorFragment on UploadError {  code  field  __typename}mutation FileUpload($file: Upload!) {  fileUpload(file: $file) {    uploadedFile {      ...FileFragment      __typename    }    errors {      ...UploadErrorFragment      __typename    }    __typename  }}"}"`

**Comment by leszekhanusz** [comment]
@g-londhe Please open another issue for your question, with as much information as you can provide (which backend, the code you used, ...)

**Pull request merged**
