### PR TITLE
File support

### PR DESCRIPTION
**Pull request by quasimik**
Regarding this [issue](https://github.com/graphql-python/gql/issues/68)
Following this [spec](https://github.com/jaydenseric/graphql-multipart-request-spec)
A bunch of code ripped from this [repo](https://github.com/DoctorJohn/aiogqlc/blob/a9567b322e4c8e5f618cc6eb4c1d401666b08708/aiogqlc/client.py)

### CODE REVIEW

**Comment by sreerajkksd** [comment]
@quasimik Would you have time to implement this feature in another one or two months ? I'm very much impressed with this library, but lack of file support is a bit annoying. Let me know if you want my help with anything.

**Comment by quasimik** [comment]
The core functionality is already implemented. However, it's failing some lint tests, probably quite simple to fix for someone with knowledge of the library's test process. You could go ahead and fix these errors yourself, if you'd like.

As for the core functionality, I've tried to make the code okay, but there's also some chance that I didn't follow the spec properly, or missed some corner cases, in which case extra work needs to be put in. The PR will probably attract maintainer attention once it passes the aforementioned lints.

**Comment by KingDarBoja** [comment]
No worries, the lint test are easy to fix, I will take care of those this weekend.

**Comment by leszekhanusz** [comment]
This is the next issue I would like to work on (probably next weekend?)
What I don't really like as it is:
* the files are put in the variable_values argument and we need to parse it recursively in all cases even when there is no files (99% of cases)

I would suggest to create another argument specifically for files.

Then we would need tests to get the code coverage to 100%

**Comment by leszekhanusz** [comment]
I have added tests and docs but cannot push on the PR, Did you uncheck the checkbox to allow maintainers to push to this PR ?

**Comment by leszekhanusz** [comment]
So, because I don't have access to your repo, I created a PR for this PR.
[https://github.com/quasimik/gql/pull/1](https://github.com/quasimik/gql/pull/1)

Please accept it 😁

**Comment by leszekhanusz** [comment]
Thanks for your help.
PR continues in #145
Comments are welcome.

**Pull request closed without merging**
